# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finansuri.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
import sys






class Ui_main_title_3(object):
    def setupUi(self, main_title_3):
        main_title_3.setObjectName("main_title_3")
        main_title_3.setEnabled(True)
        main_title_3.resize(1325, 1500)
        main_title_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(main_title_3)
        self.centralwidget.setObjectName("centralwidget")
        self.shemosavali_title = QtWidgets.QLabel(self.centralwidget)
        self.shemosavali_title.setGeometry(QtCore.QRect(30, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.shemosavali_title.setFont(font)
        self.shemosavali_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.shemosavali_title.setObjectName("shemosavali_title")
        self.shemosavali = QtWidgets.QTextEdit(self.centralwidget)
        self.shemosavali.setGeometry(QtCore.QRect(10, 60, 151, 31))
        self.shemosavali.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.shemosavali.setObjectName("shemosavali")
        self.main_title = QtWidgets.QLabel(self.centralwidget)
        self.main_title.setGeometry(QtCore.QRect(0, -1, 651, 31))
        font = QtGui.QFont()
        font.setFamily("AcadMtavr")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.main_title.setFont(font)
        self.main_title.setStyleSheet("background-color: rgb(217, 145, 0);\n"
"color: rgb(255, 255, 255);")
        self.main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.main_title.setObjectName("main_title")
        self.fasnamati_title = QtWidgets.QLabel(self.centralwidget)
        self.fasnamati_title.setGeometry(QtCore.QRect(40, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.fasnamati_title.setFont(font)
        self.fasnamati_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.fasnamati_title.setObjectName("fasnamati_title")
        self.fasnamati = QtWidgets.QTextEdit(self.centralwidget)
        self.fasnamati.setGeometry(QtCore.QRect(10, 130, 151, 31))
        self.fasnamati.setStyleSheet("color: rgb(0, 0, 0);")
        self.fasnamati.setObjectName("fasnamati")
        self.tvitgirebuleba_title = QtWidgets.QLabel(self.centralwidget)
        self.tvitgirebuleba_title.setGeometry(QtCore.QRect(10, 170, 140, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tvitgirebuleba_title.setFont(font)
        self.tvitgirebuleba_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tvitgirebuleba_title.setObjectName("tvitgirebuleba_title")
        self.mogeba_title = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_title.setGeometry(QtCore.QRect(50, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mogeba_title.setFont(font)
        self.mogeba_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_title.setObjectName("mogeba_title")
        self.komunaluri_title = QtWidgets.QLabel(self.centralwidget)
        self.komunaluri_title.setGeometry(QtCore.QRect(250, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.komunaluri_title.setFont(font)
        self.komunaluri_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.komunaluri_title.setObjectName("komunaluri_title")
        self.komunaluri = QtWidgets.QTextEdit(self.centralwidget)
        self.komunaluri.setGeometry(QtCore.QRect(250, 60, 151, 31))
        self.komunaluri.setStyleSheet("color: rgb(0, 0, 0);")
        self.komunaluri.setObjectName("komunaluri")
        self.transport_title = QtWidgets.QLabel(self.centralwidget)
        self.transport_title.setGeometry(QtCore.QRect(260, 100, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.transport_title.setFont(font)
        self.transport_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.transport_title.setObjectName("transport_title")
        self.transport = QtWidgets.QTextEdit(self.centralwidget)
        self.transport.setGeometry(QtCore.QRect(250, 130, 151, 31))
        self.transport.setStyleSheet("color: rgb(0, 0, 0);")
        self.transport.setObjectName("transport")
        self.ijara_title = QtWidgets.QLabel(self.centralwidget)
        self.ijara_title.setGeometry(QtCore.QRect(300, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ijara_title.setFont(font)
        self.ijara_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.ijara_title.setObjectName("ijara_title")
        self.ijara = QtWidgets.QTextEdit(self.centralwidget)
        self.ijara.setGeometry(QtCore.QRect(250, 200, 151, 31))
        self.ijara.setStyleSheet("color: rgb(0, 0, 0);")
        self.ijara.setObjectName("ijara")
        self.xelfasi_title = QtWidgets.QLabel(self.centralwidget)
        self.xelfasi_title.setGeometry(QtCore.QRect(290, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.xelfasi_title.setFont(font)
        self.xelfasi_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.xelfasi_title.setObjectName("xelfasi_title")
        self.xelfasi = QtWidgets.QTextEdit(self.centralwidget)
        self.xelfasi.setGeometry(QtCore.QRect(250, 270, 151, 31))
        self.xelfasi.setStyleSheet("color: rgb(0, 0, 0);")
        self.xelfasi.setObjectName("xelfasi")
        self.sagadasaxado_title = QtWidgets.QLabel(self.centralwidget)
        self.sagadasaxado_title.setGeometry(QtCore.QRect(500, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sagadasaxado_title.setFont(font)
        self.sagadasaxado_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sagadasaxado_title.setObjectName("sagadasaxado_title")
        self.sagadasaxado = QtWidgets.QTextEdit(self.centralwidget)
        self.sagadasaxado.setGeometry(QtCore.QRect(490, 60, 151, 31))
        self.sagadasaxado.setStyleSheet("color: rgb(0, 0, 0);")
        self.sagadasaxado.setObjectName("sagadasaxado")
        self.sxvaxarji_title = QtWidgets.QLabel(self.centralwidget)
        self.sxvaxarji_title.setGeometry(QtCore.QRect(520, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sxvaxarji_title.setFont(font)
        self.sxvaxarji_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sxvaxarji_title.setObjectName("sxvaxarji_title")
        self.sxvaxarji = QtWidgets.QTextEdit(self.centralwidget)
        self.sxvaxarji.setGeometry(QtCore.QRect(490, 130, 151, 31))
        self.sxvaxarji.setStyleSheet("color: rgb(0, 0, 0);")
        self.sxvaxarji.setObjectName("sxvaxarji")
        self.dividend_title = QtWidgets.QLabel(self.centralwidget)
        self.dividend_title.setGeometry(QtCore.QRect(520, 170, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dividend_title.setFont(font)
        self.dividend_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.dividend_title.setObjectName("dividend_title")
        self.dividend = QtWidgets.QTextEdit(self.centralwidget)
        self.dividend.setGeometry(QtCore.QRect(490, 200, 151, 31))
        self.dividend.setStyleSheet("color: rgb(0, 0, 0);")
        self.dividend.setObjectName("dividend")
        self.wmindamogeba_title = QtWidgets.QLabel(self.centralwidget)
        self.wmindamogeba_title.setGeometry(QtCore.QRect(510, 240, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.wmindamogeba_title.setFont(font)
        self.wmindamogeba_title.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.wmindamogeba_title.setObjectName("wmindamogeba_title")
        self.btn_title = QtWidgets.QPushButton(self.centralwidget)
        self.btn_title.setGeometry(QtCore.QRect(280, 320, 100, 40))
        self.btn_title.setStyleSheet("font: 12pt \"AcadMtavr\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius:10px;\n"
"")
        self.btn_title.setObjectName("btn_title")
        self.mogeba_label = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_label.setGeometry(QtCore.QRect(70, 270, 61, 20))
        self.mogeba_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_label.setObjectName("mogeba_label")
        self.wmindamogeba_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.wmindamogeba_label_2.setGeometry(QtCore.QRect(560, 270, 71, 20))
        self.wmindamogeba_label_2.setStyleSheet("color: rgb(0, 154, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.wmindamogeba_label_2.setObjectName("wmindamogeba_label_2")
        self.tvitgirebuleba_label = QtWidgets.QLabel(self.centralwidget)
        self.tvitgirebuleba_label.setGeometry(QtCore.QRect(70, 200, 61, 20))
        self.tvitgirebuleba_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tvitgirebuleba_label.setObjectName("tvitgirebuleba_label")
        self.main_title_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_title_2.setGeometry(QtCore.QRect(650, 0, 681, 30))
        font = QtGui.QFont()
        font.setFamily("AcadMtavr")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.main_title_2.setFont(font)
        self.main_title_2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.main_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.main_title_2.setObjectName("main_title_2")
        self.cashe_title = QtWidgets.QLabel(self.centralwidget)
        self.cashe_title.setGeometry(QtCore.QRect(700, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cashe_title.setFont(font)
        self.cashe_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.cashe_title.setObjectName("cashe_title")
        self.cashe = QtWidgets.QTextEdit(self.centralwidget)
        self.cashe.setGeometry(QtCore.QRect(710, 60, 151, 31))
        self.cashe.setStyleSheet("color: rgb(0, 0, 0);")
        self.cashe.setObjectName("cashe")
        self.maragebi_title = QtWidgets.QLabel(self.centralwidget)
        self.maragebi_title.setGeometry(QtCore.QRect(750, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.maragebi_title.setFont(font)
        self.maragebi_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.maragebi_title.setObjectName("maragebi_title")
        self.maragebi = QtWidgets.QTextEdit(self.centralwidget)
        self.maragebi.setGeometry(QtCore.QRect(710, 130, 151, 31))
        self.maragebi.setStyleSheet("color: rgb(0, 0, 0);")
        self.maragebi.setObjectName("maragebi")
        self.cashe_transit_title = QtWidgets.QLabel(self.centralwidget)
        self.cashe_transit_title.setGeometry(QtCore.QRect(740, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cashe_transit_title.setFont(font)
        self.cashe_transit_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.cashe_transit_title.setObjectName("cashe_transit_title")
        self.cashe_transit = QtWidgets.QTextEdit(self.centralwidget)
        self.cashe_transit.setGeometry(QtCore.QRect(710, 200, 151, 31))
        self.cashe_transit.setStyleSheet("color: rgb(0, 0, 0);")
        self.cashe_transit.setObjectName("cashe_transit")
        self.bank_count_title = QtWidgets.QLabel(self.centralwidget)
        self.bank_count_title.setGeometry(QtCore.QRect(720, 240, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bank_count_title.setFont(font)
        self.bank_count_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.bank_count_title.setObjectName("bank_count_title")
        self.bank_count = QtWidgets.QTextEdit(self.centralwidget)
        self.bank_count.setGeometry(QtCore.QRect(710, 270, 151, 31))
        self.bank_count.setStyleSheet("color: rgb(0, 0, 0);")
        self.bank_count.setObjectName("bank_count")
        self.lic_active_title = QtWidgets.QLabel(self.centralwidget)
        self.lic_active_title.setGeometry(QtCore.QRect(710, 310, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lic_active_title.setFont(font)
        self.lic_active_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lic_active_title.setObjectName("lic_active_title")
        self.lic_active_label = QtWidgets.QLabel(self.centralwidget)
        self.lic_active_label.setGeometry(QtCore.QRect(770, 340, 81, 20))
        self.lic_active_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lic_active_label.setObjectName("lic_active_label")
        self.debit_title = QtWidgets.QLabel(self.centralwidget)
        self.debit_title.setGeometry(QtCore.QRect(910, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.debit_title.setFont(font)
        self.debit_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.debit_title.setObjectName("debit_title")
        self.debit = QtWidgets.QTextEdit(self.centralwidget)
        self.debit.setGeometry(QtCore.QRect(910, 60, 151, 31))
        self.debit.setStyleSheet("color: rgb(0, 0, 0);")
        self.debit.setObjectName("debit")
        self.inventors_title = QtWidgets.QLabel(self.centralwidget)
        self.inventors_title.setGeometry(QtCore.QRect(940, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.inventors_title.setFont(font)
        self.inventors_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.inventors_title.setObjectName("inventors_title")
        self.inventors = QtWidgets.QTextEdit(self.centralwidget)
        self.inventors.setGeometry(QtCore.QRect(910, 130, 151, 31))
        self.inventors.setStyleSheet("color: rgb(0, 0, 0);")
        self.inventors.setObjectName("inventors")
        self.furniture_title = QtWidgets.QLabel(self.centralwidget)
        self.furniture_title.setGeometry(QtCore.QRect(960, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.furniture_title.setFont(font)
        self.furniture_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.furniture_title.setObjectName("furniture_title")
        self.furniture = QtWidgets.QTextEdit(self.centralwidget)
        self.furniture.setGeometry(QtCore.QRect(910, 200, 151, 31))
        self.furniture.setStyleSheet("color: rgb(0, 0, 0);")
        self.furniture.setObjectName("furniture")
        self.teqnic_title = QtWidgets.QLabel(self.centralwidget)
        self.teqnic_title.setGeometry(QtCore.QRect(910, 240, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.teqnic_title.setFont(font)
        self.teqnic_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.teqnic_title.setObjectName("teqnic_title")
        self.teqnic = QtWidgets.QTextEdit(self.centralwidget)
        self.teqnic.setGeometry(QtCore.QRect(910, 270, 151, 31))
        self.teqnic.setStyleSheet("color: rgb(0, 0, 0);")
        self.teqnic.setObjectName("teqnic")
        self.ground_title = QtWidgets.QLabel(self.centralwidget)
        self.ground_title.setGeometry(QtCore.QRect(910, 310, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ground_title.setFont(font)
        self.ground_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.ground_title.setObjectName("ground_title")
        self.ground = QtWidgets.QTextEdit(self.centralwidget)
        self.ground.setGeometry(QtCore.QRect(910, 340, 151, 31))
        self.ground.setStyleSheet("color: rgb(0, 0, 0);")
        self.ground.setObjectName("ground")
        self.main_active_title = QtWidgets.QLabel(self.centralwidget)
        self.main_active_title.setGeometry(QtCore.QRect(910, 380, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.main_active_title.setFont(font)
        self.main_active_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.main_active_title.setObjectName("main_active_title")
        self.main_active_label = QtWidgets.QLabel(self.centralwidget)
        self.main_active_label.setGeometry(QtCore.QRect(980, 410, 81, 20))
        self.main_active_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.main_active_label.setObjectName("main_active_label")
        self.all_active_title = QtWidgets.QLabel(self.centralwidget)
        self.all_active_title.setGeometry(QtCore.QRect(930, 440, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.all_active_title.setFont(font)
        self.all_active_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.all_active_title.setObjectName("all_active_title")
        self.all_active_label = QtWidgets.QLabel(self.centralwidget)
        self.all_active_label.setGeometry(QtCore.QRect(980, 470, 81, 20))
        self.all_active_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.all_active_label.setObjectName("all_active_label")
        self.credit__country_title = QtWidgets.QLabel(self.centralwidget)
        self.credit__country_title.setGeometry(QtCore.QRect(1090, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.credit__country_title.setFont(font)
        self.credit__country_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.credit__country_title.setObjectName("credit__country_title")
        self.credit_country = QtWidgets.QTextEdit(self.centralwidget)
        self.credit_country.setGeometry(QtCore.QRect(1130, 60, 151, 31))
        self.credit_country.setStyleSheet("color: rgb(0, 0, 0);")
        self.credit_country.setObjectName("credit_country")
        self.short_credit_title = QtWidgets.QLabel(self.centralwidget)
        self.short_credit_title.setGeometry(QtCore.QRect(1090, 100, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.short_credit_title.setFont(font)
        self.short_credit_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.short_credit_title.setObjectName("short_credit_title")
        self.short_credit = QtWidgets.QTextEdit(self.centralwidget)
        self.short_credit.setGeometry(QtCore.QRect(1130, 130, 151, 31))
        self.short_credit.setStyleSheet("color: rgb(0, 0, 0);")
        self.short_credit.setObjectName("short_credit")
        self.large_credit_title = QtWidgets.QLabel(self.centralwidget)
        self.large_credit_title.setGeometry(QtCore.QRect(1090, 170, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.large_credit_title.setFont(font)
        self.large_credit_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.large_credit_title.setObjectName("large_credit_title")
        self.large_credit = QtWidgets.QTextEdit(self.centralwidget)
        self.large_credit.setGeometry(QtCore.QRect(1130, 200, 151, 31))
        self.large_credit.setStyleSheet("color: rgb(0, 0, 0);")
        self.large_credit.setObjectName("large_credit")
        self.sum_pacciv_title = QtWidgets.QLabel(self.centralwidget)
        self.sum_pacciv_title.setGeometry(QtCore.QRect(1080, 240, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sum_pacciv_title.setFont(font)
        self.sum_pacciv_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(129, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sum_pacciv_title.setObjectName("sum_pacciv_title")
        self.sum_pacciv_label = QtWidgets.QLabel(self.centralwidget)
        self.sum_pacciv_label.setGeometry(QtCore.QRect(1180, 270, 81, 20))
        self.sum_pacciv_label.setStyleSheet("color: rgb(180, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sum_pacciv_label.setObjectName("sum_pacciv_label")
        self.capital_title = QtWidgets.QLabel(self.centralwidget)
        self.capital_title.setGeometry(QtCore.QRect(1120, 310, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.capital_title.setFont(font)
        self.capital_title.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.capital_title.setObjectName("capital_title")
        self.capital_label = QtWidgets.QLabel(self.centralwidget)
        self.capital_label.setGeometry(QtCore.QRect(1180, 350, 81, 20))
        self.capital_label.setStyleSheet("color: rgb(0, 154, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.capital_label.setObjectName("capital_label")
        self.main_title_4 = QtWidgets.QLabel(self.centralwidget)
        self.main_title_4.setGeometry(QtCore.QRect(129, 390, 371, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.main_title_4.setFont(font)
        self.main_title_4.setStyleSheet("background-color: rgb(255, 222, 35);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px")
        self.main_title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.main_title_4.setObjectName("main_title_4")
        self.tanxa_title = QtWidgets.QLabel(self.centralwidget)
        self.tanxa_title.setGeometry(QtCore.QRect(180, 430, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tanxa_title.setFont(font)
        self.tanxa_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tanxa_title.setObjectName("tanxa_title")
        self.tanxa = QtWidgets.QTextEdit(self.centralwidget)
        self.tanxa.setGeometry(QtCore.QRect(130, 460, 151, 31))
        self.tanxa.setStyleSheet("color: rgb(0, 0, 0);")
        self.tanxa.setObjectName("tanxa")
        self.vada_title = QtWidgets.QLabel(self.centralwidget)
        self.vada_title.setGeometry(QtCore.QRect(400, 430, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.vada_title.setFont(font)
        self.vada_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.vada_title.setObjectName("vada_title")
        self.vada = QtWidgets.QTextEdit(self.centralwidget)
        self.vada.setGeometry(QtCore.QRect(350, 460, 151, 31))
        self.vada.setStyleSheet("color: rgb(0, 0, 0);")
        self.vada.setObjectName("vada")
        self.procenti_title = QtWidgets.QLabel(self.centralwidget)
        self.procenti_title.setGeometry(QtCore.QRect(170, 500, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.procenti_title.setFont(font)
        self.procenti_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.procenti_title.setObjectName("procenti_title")
        self.procenti = QtWidgets.QTextEdit(self.centralwidget)
        self.procenti.setGeometry(QtCore.QRect(130, 530, 151, 31))
        self.procenti.setStyleSheet("color: rgb(0, 0, 0);")
        self.procenti.setObjectName("procenti")
        self.shenatani_title = QtWidgets.QLabel(self.centralwidget)
        self.shenatani_title.setGeometry(QtCore.QRect(390, 500, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.shenatani_title.setFont(font)
        self.shenatani_title.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.shenatani_title.setObjectName("shenatani_title")
        self.mogeba_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_label_2.setGeometry(QtCore.QRect(420, 540, 81, 20))
        self.mogeba_label_2.setStyleSheet("color: rgb(0, 154, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_label_2.setObjectName("mogeba_label_2")
        self.btn_title_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_title_2.setGeometry(QtCore.QRect(160, 580, 100, 40))
        self.btn_title_2.setStyleSheet("font: 12pt \"AcadMtavr\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius:10px")
        self.btn_title_2.setObjectName("btn_title_2")
        self.mogeba_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_label_3.setGeometry(QtCore.QRect(300, 580, 411, 31))
        self.mogeba_label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_label_3.setText("")
        self.mogeba_label_3.setObjectName("mogeba_label_3")
        self.btn_title_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_title_3.setGeometry(QtCore.QRect(940, 510, 100, 40))
        self.btn_title_3.setStyleSheet("font: 12pt \"AcadMtavr\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"border-radius:10px")
        self.btn_title_3.setObjectName("btn_title_3")
        self.mogeba_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_label_4.setGeometry(QtCore.QRect(840, 580, 411, 31))
        self.mogeba_label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_label_4.setText("")
        self.mogeba_label_4.setObjectName("mogeba_label_4")
        self.mogeba_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.mogeba_label_5.setGeometry(QtCore.QRect(420, 330, 261, 31))
        self.mogeba_label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.mogeba_label_5.setText("")
        self.mogeba_label_5.setObjectName("mogeba_label_5")
        self.all_active_title_2 = QtWidgets.QLabel(self.centralwidget)
        self.all_active_title_2.setGeometry(QtCore.QRect(1000, 650, 311, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.all_active_title_2.setFont(font)
        self.all_active_title_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.all_active_title_2.setObjectName("all_active_title_2")
        self.all_active_title_3 = QtWidgets.QLabel(self.centralwidget)
        self.all_active_title_3.setGeometry(QtCore.QRect(590, 650, 81, 21))
        font = QtGui.QFont()
        font.setFamily("AcadMtavr")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.all_active_title_3.setFont(font)
        self.all_active_title_3.setStyleSheet("color: rgb(240, 255, 67);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 255);\n"
"font: 16pt \"AcadMtavr\";\n"
"")
        self.all_active_title_3.setObjectName("all_active_title_3")
        self.all_active_title_4 = QtWidgets.QLabel(self.centralwidget)
        self.all_active_title_4.setGeometry(QtCore.QRect(680, 650, 101, 21))
        font = QtGui.QFont()
        font.setFamily("AcadMtavr")
        font.setPointSize(16)
        font.setItalic(False)
        self.all_active_title_4.setFont(font)
        self.all_active_title_4.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 16pt \"AcadMtavr\";\n"
"")
        self.all_active_title_4.setObjectName("all_active_title_4")
        self.anuitetijami_title = QtWidgets.QLabel(self.centralwidget)
        self.anuitetijami_title.setGeometry(QtCore.QRect(530, 500, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.anuitetijami_title.setFont(font)
        self.anuitetijami_title.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.anuitetijami_title.setObjectName("anuitetijami_title")
        self.anuitetijami_label = QtWidgets.QLabel(self.centralwidget)
        self.anuitetijami_label.setGeometry(QtCore.QRect(530, 540, 81, 20))
        self.anuitetijami_label.setStyleSheet("color: rgb(0, 154, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.anuitetijami_label.setObjectName("anuitetijami_label")
        self.anuitetiprocenti_title = QtWidgets.QLabel(self.centralwidget)
        self.anuitetiprocenti_title.setGeometry(QtCore.QRect(640, 500, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.anuitetiprocenti_title.setFont(font)
        self.anuitetiprocenti_title.setStyleSheet("color: rgb(180, 0, 0);\n"
"font: 8pt \"AcadMtavr\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.anuitetiprocenti_title.setObjectName("anuitetiprocenti_title")
        self.anuitetiprocenti_label = QtWidgets.QLabel(self.centralwidget)
        self.anuitetiprocenti_label.setGeometry(QtCore.QRect(640, 540, 81, 20))
        self.anuitetiprocenti_label.setStyleSheet("color: rgb(180, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.anuitetiprocenti_label.setObjectName("anuitetiprocenti_label")
        self.shemosavali.raise_()
        self.main_title.raise_()
        self.fasnamati.raise_()
        self.tvitgirebuleba_title.raise_()
        self.mogeba_title.raise_()
        self.komunaluri_title.raise_()
        self.komunaluri.raise_()
        self.transport_title.raise_()
        self.transport.raise_()
        self.ijara_title.raise_()
        self.ijara.raise_()
        self.xelfasi_title.raise_()
        self.xelfasi.raise_()
        self.sagadasaxado_title.raise_()
        self.sagadasaxado.raise_()
        self.sxvaxarji_title.raise_()
        self.sxvaxarji.raise_()
        self.dividend_title.raise_()
        self.dividend.raise_()
        self.wmindamogeba_title.raise_()
        self.btn_title.raise_()
        self.shemosavali_title.raise_()
        self.fasnamati_title.raise_()
        self.mogeba_label.raise_()
        self.wmindamogeba_label_2.raise_()
        self.tvitgirebuleba_label.raise_()
        self.main_title_2.raise_()
        self.cashe_title.raise_()
        self.cashe.raise_()
        self.maragebi_title.raise_()
        self.maragebi.raise_()
        self.cashe_transit_title.raise_()
        self.cashe_transit.raise_()
        self.bank_count_title.raise_()
        self.bank_count.raise_()
        self.lic_active_title.raise_()
        self.lic_active_label.raise_()
        self.debit_title.raise_()
        self.debit.raise_()
        self.inventors_title.raise_()
        self.inventors.raise_()
        self.furniture_title.raise_()
        self.furniture.raise_()
        self.teqnic_title.raise_()
        self.teqnic.raise_()
        self.ground_title.raise_()
        self.ground.raise_()
        self.main_active_title.raise_()
        self.main_active_label.raise_()
        self.all_active_title.raise_()
        self.all_active_label.raise_()
        self.credit__country_title.raise_()
        self.credit_country.raise_()
        self.short_credit_title.raise_()
        self.short_credit.raise_()
        self.large_credit_title.raise_()
        self.large_credit.raise_()
        self.sum_pacciv_title.raise_()
        self.sum_pacciv_label.raise_()
        self.capital_title.raise_()
        self.capital_label.raise_()
        self.main_title_4.raise_()
        self.tanxa_title.raise_()
        self.tanxa.raise_()
        self.vada_title.raise_()
        self.vada.raise_()
        self.procenti_title.raise_()
        self.procenti.raise_()
        self.shenatani_title.raise_()
        self.mogeba_label_2.raise_()
        self.btn_title_2.raise_()
        self.mogeba_label_3.raise_()
        self.btn_title_3.raise_()
        self.mogeba_label_4.raise_()
        self.mogeba_label_5.raise_()
        self.all_active_title_2.raise_()
        self.all_active_title_3.raise_()
        self.all_active_title_4.raise_()
        self.anuitetijami_title.raise_()
        self.anuitetijami_label.raise_()
        self.anuitetiprocenti_title.raise_()
        self.anuitetiprocenti_label.raise_()
        main_title_3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_title_3)
        self.statusbar.setObjectName("statusbar")
        main_title_3.setStatusBar(self.statusbar)

        self.retranslateUi(main_title_3)
        QtCore.QMetaObject.connectSlotsByName(main_title_3)


        self.add_functions()
        self.add_functions2()
        self.add_functions3()
        self.is_aquel = False
        self.is_pti = 0
        self.request_cashe = 0


    def retranslateUi(self, main_title_3):
        _translate = QtCore.QCoreApplication.translate
        self.shemosavali_title.setText(_translate("main_title_3", "შემოსავალი"))
        self.main_title.setText(_translate("main_title_3", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">მოგება-ზარალი</span></p></body></html>"))
        self.fasnamati_title.setText(_translate("main_title_3", "ფასნამატი"))
        self.tvitgirebuleba_title.setText(_translate("main_title_3", "თვითღირებულება"))
        self.mogeba_title.setText(_translate("main_title_3", "მოგება"))
        self.komunaluri_title.setText(_translate("main_title_3", "კომუნალური ხარჯი"))
        self.transport_title.setText(_translate("main_title_3", "ტრანსპორტირება"))
        self.ijara_title.setText(_translate("main_title_3", "იჯარა"))
        self.xelfasi_title.setText(_translate("main_title_3", "ხელფასები"))
        self.sagadasaxado_title.setText(_translate("main_title_3", "საგადასახადო"))
        self.sxvaxarji_title.setText(_translate("main_title_3", "სხვა ხარჯი"))
        self.dividend_title.setText(_translate("main_title_3", "დივიდენდი"))
        self.wmindamogeba_title.setText(_translate("main_title_3", "წმინდა მოგება"))
        self.btn_title.setText(_translate("main_title_3", "გამოთვლა"))
        self.mogeba_label.setText(_translate("main_title_3", "0"))
        self.wmindamogeba_label_2.setText(_translate("main_title_3", "0"))
        self.tvitgirebuleba_label.setText(_translate("main_title_3", "0"))
        self.main_title_2.setText(_translate("main_title_3", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">ბალანსი</span></p></body></html>"))
        self.cashe_title.setText(_translate("main_title_3", "ნაღდი თანხა-სალარო"))
        self.maragebi_title.setText(_translate("main_title_3", "მარაგები"))
        self.cashe_transit_title.setText(_translate("main_title_3", "თანხა გზაში"))
        self.bank_count_title.setText(_translate("main_title_3", "საბანკო ანგარიში"))
        self.lic_active_title.setText(_translate("main_title_3", "ლიკვიდური-აქტივები"))
        self.lic_active_label.setText(_translate("main_title_3", "0"))
        self.debit_title.setText(_translate("main_title_3", "დებიტორები-ნისია"))
        self.inventors_title.setText(_translate("main_title_3", "ინვენტარი"))
        self.furniture_title.setText(_translate("main_title_3", "ავეჯი"))
        self.teqnic_title.setText(_translate("main_title_3", "ტექნიკა-დანადგარი"))
        self.ground_title.setText(_translate("main_title_3", "     უძრავი ქონება"))
        self.main_active_title.setText(_translate("main_title_3", "გრძელვადიანი აქტივები"))
        self.main_active_label.setText(_translate("main_title_3", "0"))
        self.all_active_title.setText(_translate("main_title_3", "სულ აქტივები"))
        self.all_active_label.setText(_translate("main_title_3", "0"))
        self.credit__country_title.setText(_translate("main_title_3", "საგადასახადო ვალდებულება"))
        self.short_credit_title.setText(_translate("main_title_3", "მოკლევადიანი საბანკო სესხი"))
        self.large_credit_title.setText(_translate("main_title_3", "გრძელვადიანი საბანკო სესხი"))
        self.sum_pacciv_title.setText(_translate("main_title_3", "სულ პასივები-ვალდებულებები"))
        self.sum_pacciv_label.setText(_translate("main_title_3", "0"))
        self.capital_title.setText(_translate("main_title_3", "საკუთარი კაპიტალი"))
        self.capital_label.setText(_translate("main_title_3", "0"))
        self.main_title_4.setText(_translate("main_title_3", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">სესხის თანხა-ანუიტეტი</span></p></body></html>"))
        self.tanxa_title.setText(_translate("main_title_3", "თანხა"))
        self.vada_title.setText(_translate("main_title_3", "ვადა"))
        self.procenti_title.setText(_translate("main_title_3", "პროცენტი"))
        self.shenatani_title.setText(_translate("main_title_3", "შენატანი"))
        self.mogeba_label_2.setText(_translate("main_title_3", "0"))
        self.btn_title_2.setText(_translate("main_title_3", "გამოთვლა"))
        self.btn_title_3.setText(_translate("main_title_3", "გამოთვლა"))
        self.all_active_title_2.setText(_translate("main_title_3", "@ - 2022 Copyright, All right reserved, created by Zk "))
        self.all_active_title_3.setText(_translate("main_title_3", "ლაზიკა"))
        self.all_active_title_4.setText(_translate("main_title_3", "კაპიტალი"))
        self.anuitetijami_title.setText(_translate("main_title_3", "სულ ჯამი"))
        self.anuitetijami_label.setText(_translate("main_title_3", "0"))
        self.anuitetiprocenti_title.setText(_translate("main_title_3", "სულ  %"))
        self.anuitetiprocenti_label.setText(_translate("main_title_3", "0"))



    def add_functions(self):
            self.btn_title.clicked.connect(lambda: self.write_number(self.shemosavali.toPlainText(),
            self.fasnamati.toPlainText(),self.komunaluri.toPlainText(),self.transport.toPlainText(),
            self.ijara.toPlainText(),self.xelfasi.toPlainText(),self.sagadasaxado.toPlainText(),
            self.sxvaxarji.toPlainText(),self.dividend.toPlainText()))



    def add_functions2(self):
            self.btn_title_2.clicked.connect(lambda: self.write_number2(self.tanxa.toPlainText(),
            self.vada.toPlainText(),self.procenti.toPlainText()))





    def add_functions3(self):
            self.btn_title_3.clicked.connect(lambda: self.write_number3(self.cashe.toPlainText(),
            self.maragebi.toPlainText(),self.cashe_transit.toPlainText(),
            self.bank_count.toPlainText(),self.debit.toPlainText(),self.inventors.toPlainText(),
            self.furniture.toPlainText(),self.teqnic.toPlainText(),self.ground.toPlainText(),
            self.credit_country.toPlainText(),self.short_credit.toPlainText(),self.large_credit.toPlainText()))


# class Popup(Ui_main_title_3):
#         def __init__(self):
#                 super(Popup,self).__init__()
#
#                 # app = QApplication(sys.argv)
#                 # window = QtWidgets.QMainWindow()
#                 self.setGeometry(200,400,300,300)
#                 self.SetWindowTitle('')
#                 self.show()
#                 self.sys.exit(app.exec_)
#
#         def popup(self):
#                 self.SetWindowTitle('შეავსეთ ველები')




    def write_number(self,*args):


            try:
                    # mogeba-zarali
                    val1 = float(self.shemosavali.toPlainText())
                    val2 = float(self.fasnamati.toPlainText())
                    val3 = float(self.komunaluri.toPlainText())
                    val4 = float(self.transport.toPlainText())
                    val5 = float(self.ijara.toPlainText())
                    val6 = float(self.xelfasi.toPlainText())
                    val7 = float(self.sagadasaxado.toPlainText())
                    val8 = float(self.sxvaxarji.toPlainText())
                    val9 = float(self.dividend.toPlainText())



                    total_fas = (val2/100)+1
                    total_tvit = round(val1/total_fas,2)
                    total_mogeba = round(val1-total_tvit,2)


                    total_wmindamogeba=round((total_mogeba-val3-val4-val5-val6-val7-val8-val9),2)
                    self.is_pti = total_wmindamogeba

                    if self.is_pti<=1000:
                            self.is_pti=(total_wmindamogeba*25)/100
                    else:
                            self.is_pti=(total_wmindamogeba*35)/100

                            # shemosavali1 = eval(self.shemosavali.toPlainText())
                            # fasnamati2 = eval(self.fasnamati.toPlainText())


                    # if self.mogeba_label.text() =='0':
                    #         # self.mogeba_label.setText('0')
                    #         self.mogeba_label.setText(str(total_mogeba))
                    #         self.wmindamogeba_label_2.setText(str(total_wmindamogeba))
                    #         self.tvitgirebuleba_label.setText(str(total_tvit))
                    # else:
                    #         self.mogeba_label.setText('0')
                    #         self.wmindamogeba_label_2.setText('0')
                    #         self.tvitgirebuleba_label.setText('0')
                    #         # self.mogeba_label.setText(self.mogeba_label.text()+shemosavali)

                    if self.tvitgirebuleba_label.text() =='0':
                            self.tvitgirebuleba_label.setText(str(total_tvit))
                            self.mogeba_label.setText(str(total_mogeba))
                            self.wmindamogeba_label_2.setText(str(total_wmindamogeba))
                    else:
                            self.tvitgirebuleba_label.setText('0')
                            self.mogeba_label.setText('0')
                            self.wmindamogeba_label_2.setText('0')

                    # if self.wmindamogeba_label_2.text() =='0':
                    #         self.wmindamogeba_label_2.setText(str(total_wmindamogeba))
                    # else:
                    #         self.wmindamogeba_label_2.setText('0')
            except:

                    self.wmindamogeba_label_2.setText('0')
                    self.tvitgirebuleba_label.setText('0')
                    self.mogeba_label.setText('0')







    #anuiteti grafiki

    def write_number2(self,*args):
            try:

                    val10 = float(self.tanxa.toPlainText())
                    val11 = float(self.vada.toPlainText())
                    val12 = float(self.procenti.toPlainText())
                    self.request_cashe=val10
                    total_procenti =(val12 * 0.57)
                    total_tanxa = ((val10*total_procenti)/100/12)*val11+val10
                    total_shenatani=round(total_tanxa/val11,2)
                    self.request_cashe=val10


                    total_anuiteti_procenti = round(total_tanxa-val10,2)
                    total_tanxa = round(total_tanxa,2)

                    if self.is_pti<total_shenatani and self.is_aquel==False:
                            self.mogeba_label_2.setText(str(total_shenatani))
                            self.mogeba_label_3.setText('PTI კოეფიციენტი არ ემსახურება...')
                            self.is_aquel=False

                            self.anuitetijami_label.setText(str(total_tanxa))
                            self.anuitetiprocenti_label.setText(str(total_anuiteti_procenti))




                    if self.is_pti>total_shenatani and self.is_aquel==False:
                            self.mogeba_label_2.setText(str(total_shenatani))
                            self.mogeba_label_3.setText('')
                            self.is_aquel=True

                            self.anuitetijami_label.setText(str(total_tanxa))
                            self.anuitetiprocenti_label.setText(str(total_anuiteti_procenti))


                            if self.mogeba_label_2.text() =='0' or self.is_aquel:
                                    self.mogeba_label_2.setText(str(total_shenatani))
                                    self.mogeba_label_3.setText('')
                                    self.is_aquel = False


                            else:
                                    self.mogeba_label_2.setText(str('0'))
                                    self.mogeba_label_3.setText('')
                                    self.is_aquel = False
                                    self.anuitetijami_label.setText(str('0'))
                                    self.anuitetiprocenti_label.setText(str('0'))
            except:
                    self.mogeba_label_3.setText('არასწორი მნიშვნელობა,შეავსეთ ველები..')
                    self.mogeba_label_2.setText('')
                    self.anuitetijami_label.setText('')
                    self.anuitetiprocenti_label.setText('')
                    # self.is_aquel = False









    def write_number3(self,*args):
            try:
                    val13 = float(self.cashe.toPlainText())
                    val14 = float(self.maragebi.toPlainText())
                    val15 = float(self.cashe_transit.toPlainText())
                    val16 = float(self.bank_count.toPlainText())
                    val17 = float(self.debit.toPlainText())
                    val18 = float(self.inventors.toPlainText())
                    val19 = float(self.furniture.toPlainText())
                    val20 = float(self.teqnic.toPlainText())
                    val21 = float(self.ground.toPlainText())
                    val22 = float(self.credit_country.toPlainText())
                    val23 = float(self.short_credit.toPlainText())
                    val24 = float(self.large_credit.toPlainText())


                    total_lic_active =round(val13+val14+val15+val16,2)
                    total_main_active =round(val17+val18+val19+val20+val21,2)
                    total_sum_active =round(total_lic_active+total_main_active,2)
                    total_sum_passive = round(val22+val23+val24,2)
                    total_capital = round(total_sum_active-total_sum_passive,2)


                    if self.request_cashe > total_capital :
                            self.mogeba_label_4.setText('საკუთარი კაპიტალი ნაკლებია მოთხოვნილ თანხაზე..!')
                    else:
                            self.mogeba_label_4.setText('')


                    if self.lic_active_label.text() =='0':
                            self.lic_active_label.setText(str(total_lic_active))

                    else:
                            self.lic_active_label.setText('0')

                    if self.main_active_label.text() =='0':
                            self.main_active_label.setText(str(total_main_active))

                    else:
                            self.main_active_label.setText('0')

                    if self.all_active_label.text() =='0':
                            self.all_active_label.setText(str(total_sum_active))
                    else:
                            self.all_active_label.setText('0')

                    if self.sum_pacciv_label.text() =='0':
                            self.sum_pacciv_label.setText(str(total_sum_passive))
                    else:
                            self.sum_pacciv_label.setText('0')

                    if self.capital_label.text() =='0':
                            self.capital_label.setText(str(total_capital))
                    else:
                            self.capital_label.setText('0')
            except:
                    self.mogeba_label_4.setText('არასწორი მნიშვნელობა,შეავსეთ ველები..')






            # if self.wmindamogeba_label_2.text() =='0':
            #     self.wmindamogeba_label_2.setText(str(total_wmindamogeba))
            # else:
            #     self.wmindamogeba_label_2.setText('0')




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_title_3 = QtWidgets.QMainWindow()
    ui = Ui_main_title_3()
    ui.setupUi(main_title_3)
    main_title_3.show()
    sys.exit(app.exec_())
